
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ALTERNATYWA CALKOWITA DOPOKI DZIELENIE GLOWNY ID JEZELI KOMENTARZ_JEDNOLINIJKOWY KOMENTARZ_WIELOLINIJKOWY KONIUNKCJA LEWA_KLAMRA LEWY_NAWIAS LICZBA MINUS MNIEJSZE MNIEJSZE_ROWNE NEGACJA PLUS PRAWA_KLAMRA PRAWY_NAWIAS PRZYPISANIE RAZY ROWNE SREDNIK WCZYTAJ WIEKSZE WIEKSZE_ROWNE WYPISZprogram : GLOWNY LEWA_KLAMRA wyrazenia PRAWA_KLAMRA wyrazenia : wyrazenia wyrazenie\n                 | epsilonwyrazenie : CALKOWITA ID PRZYPISANIE LICZBA SREDNIKepsilon :'
    
_lr_action_items = {'GLOWNY':([0,],[2,]),'$end':([1,6,],[0,-1,]),'LEWA_KLAMRA':([2,],[3,]),'PRAWA_KLAMRA':([3,4,5,7,12,],[-5,6,-3,-2,-4,]),'CALKOWITA':([3,4,5,7,12,],[-5,8,-3,-2,-4,]),'ID':([8,],[9,]),'PRZYPISANIE':([9,],[10,]),'LICZBA':([10,],[11,]),'SREDNIK':([11,],[12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'wyrazenia':([3,],[4,]),'epsilon':([3,],[5,]),'wyrazenie':([4,],[7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> GLOWNY LEWA_KLAMRA wyrazenia PRAWA_KLAMRA','program',4,'p_program','parser.py',6),
  ('wyrazenia -> wyrazenia wyrazenie','wyrazenia',2,'p_wyrazenia','parser.py',10),
  ('wyrazenia -> epsilon','wyrazenia',1,'p_wyrazenia','parser.py',11),
  ('wyrazenie -> CALKOWITA ID PRZYPISANIE LICZBA SREDNIK','wyrazenie',5,'p_wyrazenie','parser.py',18),
  ('epsilon -> <empty>','epsilon',0,'p_epsilon','parser.py',22),
]
